language: c

dist: 
 - xenial

# Setup Build Matrix
compiler: 
 - clang
 - gcc

env:
  global:
    - COVERITY_SCAN_PROJECT_NAME="chan-sccp/chan-sccp"
    - COVERITY_SCAN_PROJECT_DESCRIPTION="SCCP Channel Addon for Asterisk"
    - COVERITY_SCAN_NOTIFICATION_EMAIL="info@talon.nl"
    # COVERITY_SCAN_BRANCH_PATTERN="master"
    - COVERITY_SCAN_BRANCH_PATTERN="develop"
    - COVERITY_SCAN_BUILD_URL="https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh"
    - COVERITY_SCAN_BUILD="curl -s $COVERITY_SCAN_BUILD_URL | bash"
    - COVERITY_SCAN_BUILD_COMMAND_PREPEND="./configure --enable-video --enable-conference --enable-distributed-devicestate --enable-advanced-functions && make clean"
    - COVERITY_SCAN_BUILD_COMMAND="make -j2"
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created using: travis encrypt COVERITY_SCAN_TOKEN="xxxxxxx-xxxxxxx" -r dkgroot/chan-sccp-b
    - secure: "VJIQBkTBxuMqUEk872yPrbPq3MAFqB0EnjElxjTk+BWEHIKmheKIHyrlqJgnql/tqyeLSa6D8epV0cJ47adVbedCPAG/l1tk4AzErrQdnw9VVFANUFrJXxlaH/yfm39XiwwumuAJ2RF3OaYGHlyurW+lb91y2HHw8vQHNPu+uHI="
  matrix:
    - REPOS=xenial   # TLS
    - REPOS=coverity # Xenial TLS
    - REPOS=bionic   # TLS
#    - REPOS=cosmic
#    - REPOS=disco

matrix:
  allow_failures:
    - compiler: clang
      env: REPOS=coverity

# Install Required Devel Packages
before_install:
 - if [ "${REPOS}" != "coverity" ]; 
   then
     sudo apt-get update -qq;
     sudo apt-get install -qq libblocksruntime0 libblocksruntime-dev libpj2 libpjmedia2 libpjnath2 libpjproject-dev libpjsip2 libpjsua2 asterisk asterisk-dev asterisk-config asterisk-modules asterisk-dbg binutils.dev libc6-dev gettext  autoconf automake m4 autotools-dev libltdl-dev;
   else
     sudo apt-get update -qq;
     sudo apt-get install -qq libblocksruntime0 libblocksruntime-dev libpj2 libpjmedia2 libpjnath2 libpjproject-dev libpjsip2 libpjsua2 asterisk asterisk-dev asterisk-config asterisk-modules asterisk-dbg binutils.dev libc6-dev gettext  autoconf automake m4 autotools-dev libltdl-dev;
     if [ "x${CC}" == "xclang" ] && [ "x${TRAVIS_BRANCH}" == "xdevelop" ]; then eval "$COVERITY_SCAN_BUILD"; fi;
   fi

# Prepare Configure Script
before_script:
 - autoreconf -fi

# Report Results
notifications:
  slack: chan-sccp:yfQzKYTnTf4cD1iHElnTYsXD
  email:
    recipients:
      - ddegroot@talon.nl
      - marcelloceschia@users.sourceforge.net
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2d18f92f8374e4e15fbc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
