language: c

dist: 
 - xenial

# Setup Build Matrix
compiler: 
 - clang
 - gcc

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created using: travis encrypt COVERITY_SCAN_TOKEN="xxxxxxx-xxxxxxx" -r dkgroot/chan-sccp-b
   - secure: "ambC8BbKKCJRW/6iwwNS7xfcAg2X00jZsK0McvwpFUEBylxypUni2aBdOpOyMcUGd5hQJS16XbcObeBCim2ZYnyAUzR2LKoFZroGVbwN83OhLGJ83cSXgiDbzKUxuBKTwonUocB7HxWuFJLN1OXb9gucwQNWbLC2VuV5tTsp/NY="

  matrix:
    - REPOS=xenial   # TLS
    - REPOS=coverity # Xenial TLS
    - REPOS=bionic   # TLS
#    - REPOS=cosmic
#    - REPOS=disco

matrix:
  allow_failures:
    - compiler: clang
      env: COVERITY_SCAN_BRANCH_PATTERN=develop

# Install Required Devel Packages
before_install:
 -  sudo apt-get update -qq
 -  sudo apt-get install -qq libblocksruntime0 libblocksruntime-dev libpj2 libpjmedia2 libpjnath2 libpjproject-dev libpjsip2 libpjsua2 asterisk asterisk-dev asterisk-config asterisk-modules asterisk-dbg binutils.dev libc6-dev gettext  autoconf automake m4 autotools-dev libltdl-dev libxml2-dev libxslt1-dev
# asterisk-tests

# Prepare Configure Script
before_script:
 - autoreconf -fi
 
# temporary additiong to run with "xml"
script:
 - ./configure --enable-video --enable-conference --enable-distributed-devicestate --enable-advanced-functions --enable-experimental-xml && make clean && make && make test

after_script:
 - cat /home/travis/build/chan-sccp/chan-sccp/cov-int/scm_log.txt

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

# Report Results
notifications:
  slack: chan-sccp:yfQzKYTnTf4cD1iHElnTYsXD
  email:
    recipients:
      - ddegroot@talon.nl
      - marcelloceschia@users.sourceforge.net
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2d18f92f8374e4e15fbc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

addons:
  coverity_scan:
    project:
      name: chan-sccp/chan-sccp
      description: "Replacement for the SCCP channel driver in Asterisk. Extended features include Shared Lines, Presence / BLF, customizable Feature Buttons, and Custom Device State. Visit our discussion mailing list for help and join us as a developer if you like."
    notification_email: ddegroot@talon.nl
    build_command_prepend: ./configure --enable-video --enable-conference --enable-distributed-devicestate --enable-advanced-functions --enable-experimental-xml && make clean
    build_command: make -j2
    branch_pattern: develop
    
    
