name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: apt install asterisk
    - name: configure
      run: ./configure --enable-conference --enable-devdoc --with-hash-size=3001 --enable-experimental-xml --enable-video
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
